### ISSUE TITLE
没办法安装啊

### ISSUE THREAD

**Issue by condatacloud** [energye/systray#1]
确定是 import "energye/systray" 这样导入吗？

**Comment by sxmxta** [comment]
run example: go run main.go

**Comment by davidnewhall** [comment]
The `API` example in the [README.md](https://github.com/energye/systray/blob/main/README.md#api) file is also missing the `github.com` prefix.

**Comment by sxmxta** [comment]
> [README.md](https://github.com/energye/systray/blob/main/README.md#api) 文件中的示例也缺少前缀。`API``github.com`

github.com added
