### ISSUE TITLE
Open menu with left click

### ISSUE THREAD

**Issue by davidnewhall** [energye/systray#4]
I might be missing something obvious. Is it possible to open the menu with left click?

**Comment by sxmxta** [comment]
I remember adding events for the left and right mouse buttons to control the tray menu

**Comment by davidnewhall** [comment]
I found these methods. 

[func SetOnClick(fn func())](https://pkg.go.dev/github.com/energye/systray#SetOnClick)
[func SetOnDClick(fn func())](https://pkg.go.dev/github.com/energye/systray#SetOnDClick)
[func SetOnRClick(fn func(menu IMenu))](https://pkg.go.dev/github.com/energye/systray#SetOnRClick)

It seems like only `SetOnRClick` provides the `IMenu`. I'm able to open the menu with right click, but have not figured out how to do it with left click.

**Comment by sxmxta** [comment]
> I found these methods.
> 
> [func SetOnClick(fn func())](https://pkg.go.dev/github.com/energye/systray#SetOnClick) [func SetOnDClick(fn func())](https://pkg.go.dev/github.com/energye/systray#SetOnDClick) [func SetOnRClick(fn func(menu IMenu))](https://pkg.go.dev/github.com/energye/systray#SetOnRClick)
> 
> It seems like only `SetOnRClick` provides the `IMenu`. I'm able to open the menu with right click, but have not figured out how to do it with left click.

v1.0.1 has added the menu parameter to the click event

**Comment by davidnewhall** [comment]
Thank you!
