### ISSUE TITLE
How to change tray icon?

### ISSUE THREAD

**Issue by solomongrundy6** [energye/systray#7]
Used this project to make a couple of system tray programs and it's working pretty well.  But I can't figure out how to change the current icon in the tray to signify things to the user at a glance.  Whenever I try to use SetTemplateIcon again, I get:

`2023/09/03 12:16:26 systray error: failed to set IconPixmap prop: dbus.Store: type mismatch: slice: cannot convert a value of []systray.PX into []systray.PX`

How do I change the current systray icon? Is it possible?

**Comment by solomongrundy6** [comment]
Nevermind, I found this commit in one of [the higher systray forks](https://github.com/fyne-io/systray/pull/49/commits/e10c33610bf3d56c287119e9435c347f8cba0e54)

This fixes the problem.

**Comment by sxmxta** [comment]
Fixed the issue
