### ISSUE TITLE
PopOS not respecting the left mouse click...

### ISSUE THREAD

**Issue by precisionpete** [energye/systray#8]
I have the following code I am building on Mint 21.2/Cinnamon (Ubuntu 22.04). I am building a Wails v2/Sveltekit app. 

It works great on Mint and also Windows. But on PopOS 22.04, it shows up in the top panel, but both the left and right clicks trigger the right click?  

I have no idea how to debug this... Any ideas?
```
func stOnReady() {
	systray.SetIcon(icons.SysIcon)
	systray.SetTemplateIcon(icons.SysIcon, icons.SysIcon)
	systray.SetTitle("Wails1")
	systray.SetTooltip("Wails App")

	systray.SetOnClick(func(menu systray.IMenu) {
		_ = menu
		toggleWindow()
	})

	systray.SetOnRClick(func(menu systray.IMenu) {
		menu.ShowMenu()
	})

	mQuit := systray.AddMenuItem("Quit", "Quit the whole app")
	mQuit.Click(func() { os.Exit(0) })

}
```

**Comment by sxmxta** [comment]
Poor support for Linux events
